services:
   financeapp:
      build: 
        context: .
        dockerfile: Dockerfile
      volumes:
         - .:/home/app
      ports:
         - 3000:3000
      depends_on:
         - db
      environment:
         - NODE_ENV=development

   db:
      image: mongo:6.0
      environment:
         MONGODB_INITDB_ROOT_USERNAME: root
         MONGODB_INITDB_ROOT_PASSWORD: root
      ports:
         - "27017:27017"
