services:
  financeapi:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/finance_db
    depends_on:
      - database
      - redis
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finance_db
    ports:
      - '5432:5432'
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
